name: Release Auparse
on:
  push:
    branches:
      - 'feature/release'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
        default: '2.6.1'

permissions:
  contents: write

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, darwin ]
        arch: [ amd64, arm64 ]
    env:
      tag: v${{ inputs.version }}-${{ matrix.os }}-${{ matrix.arch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all tags and history are fetched

      - name: Create and Push Tag if Missing
        run: |
          if ! git rev-parse "v${{ inputs.version }}" >/dev/null 2>&1; then
            git tag v${{ inputs.version }}
            git push origin v${{ inputs.version }}
          fi

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.6

      - name: Build
        run: |
          GOOS="${{ matrix.os }}" GOARCH="${{ matrix.arch }}" go build -o bin/auparse-${{ env.tag }} cmd/auparse/auparse.go 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: auparse-${{ env.tag }}
          path: bin/auparse-${{ env.tag }}

  release:
    name: Release
    runs-on: ubuntu-latest 
    needs: build
    steps:  
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all tags are fetched
          ref: v${{ inputs.version }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: bin

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/auparse-*
          name: 'Release v${{ inputs.version }}'
          tag_name: 'v${{ inputs.version }}'
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
