name: Release Auparse
on:
  push:
    branches:
      - 'feature/release'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
        default: '2.5.0'
permissions:
  contents: read
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, darwin ]
        arch: [ amd64, arm64 ]
    env:
      tag: ${{ inputs.version }}-${{ matrix.os }}-${{ matrix.arch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          tag: 'refs/tags/v${{ inputs.version }}'
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.6
      - name: Build
        run: |
          GOOS="${{ matrix.os }}" GOARCH="${{ matrix.arch }}" go build -o bin/auparse-${{ env.tag }} cmd/auparse/auparse.go 
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: auparse-${{ env.tag }}
          path: bin/auparse-${{ env.tag }}
  release:
    name: Release
    runs-on: ubuntu-latest 
    needs: build
    steps:  
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        path: bin
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: bin/auparse-*
        name: '${{ inputs.version }}'
        tag_name: '${{ inputs.version }}'
        generate_release_notes: true
        token: '${{ secrets.GITHUB_TOKEN }}'
