name: Release Auparse
on:
  push:
    tags:
      - 'v*'  # Runs only on new tag push

permissions:
  contents: write

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, darwin ]
        arch: [ amd64, arm64 ]
    env:
      tag: v${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all tags are fetched

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.6

      - name: Build
        run: |
          GOOS="${{ matrix.os }}" GOARCH="${{ matrix.arch }}" go build -o bin/auparse-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }} cmd/auparse/auparse.go 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: auparse-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}
          path: bin/auparse-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}

  release:
    name: Release
    runs-on: ubuntu-latest 
    needs: build
    steps:  
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all tags are fetched
          ref: ${{ github.ref_name }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: bin
          merge-multiple: true  # Merge all artifacts in one folder

      - name: List downloaded files
        run: ls -R bin  # Debugging step to verify files

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*
          name: 'Release ${{ github.ref_name }}'
          tag_name: '${{ github.ref_name }}'
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
